"use client"

import { useState, useEffect } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Progress } from "@/components/ui/progress"
import { CurrencyDisplay } from "@/components/ui/currency"
import {
  ArrowLeft,
  FileText,
  Download,
  BarChart3,
  TrendingUp,
  TrendingDown,
  Target,
  PiggyBank,
  AlertTriangle,
  CheckCircle,
  Zap,
  Star,
  Calendar,
  DollarSign,
} from "lucide-react"
import Link from "next/link"

interface UserData {
  name: string
  age: string
  income: string
  currency: string
  currentSavings: string
  monthlySavings: string
  goal: string
  goalAmount: string
  timeframe: string
  riskTolerance: string
  expenses: string
}

export default function ReportPage() {
  const [userData, setUserData] = useState<UserData | null>(null)
  const [mounted, setMounted] = useState(false)
  const [isGenerating, setIsGenerating] = useState(false)
  const [reportGenerated, setReportGenerated] = useState(false)

  useEffect(() => {
    setMounted(true)
    const savedData = localStorage.getItem("younance-user-data")
    if (savedData) {
      setUserData(JSON.parse(savedData))
    }
  }, [])

  const generateReport = async () => {
    setIsGenerating(true)
    // Simulate AI report generation
    await new Promise(resolve => setTimeout(resolve, 3000))
    setIsGenerating(false)
    setReportGenerated(true)
  }

  const downloadReport = () => {
    // Create a simple PDF-like content
    const reportContent = `
YouNance Financial Health Report
Generated on: ${new Date().toLocaleDateString()}
User: ${userData?.name}

FINANCIAL HEALTH SCORE: 85/100

KEY METRICS:
- Current Savings: ${userData?.currentSavings}
- Monthly Savings: ${userData?.monthlySavings}
- Goal Amount: ${userData?.goalAmount}
- Risk Tolerance: ${userData?.riskTolerance}

RECOMMENDATIONS:
1. Increase emergency fund to 6 months of expenses
2. Diversify investments across different asset classes
3. Consider increasing monthly contributions by 10%
4. Review and optimize tax-advantaged accounts

This report was generated by YouNance AI Financial Advisor.
    `
    
    const blob = new Blob([reportContent], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `younance-financial-report-${new Date().toISOString().split('T')[0]}.txt`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
  }

  if (!mounted) return null

  if (!userData) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-emerald-50 via-white to-teal-50 flex items-center justify-center">
        <Card className="max-w-md">
          <CardHeader>
            <CardTitle>Setup Required</CardTitle>
            <CardDescription>Please complete your profile setup to generate a financial report</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <Link href="/setup">
              <Button className="w-full bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-700 hover:to-teal-700">
                Complete Setup
              </Button>
            </Link>
            <Link href="/dashboard">
              <Button variant="outline" className="w-full">
                Back to Dashboard
              </Button>
            </Link>
          </CardContent>
        </Card>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-emerald-50 via-white to-teal-50">
      {/* Header */}
      <header className="bg-white/80 backdrop-blur-sm border-b border-emerald-100/50 sticky top-0 z-50">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-4">
              <Link href="/dashboard">
                <Button variant="ghost" size="sm" className="hover:bg-emerald-50">
                  <ArrowLeft className="h-4 w-4 mr-2" />
                  Back to Dashboard
                </Button>
              </Link>
              <div>
                <h1 className="text-2xl font-bold bg-gradient-to-r from-emerald-600 to-teal-600 bg-clip-text text-transparent">
                  AI Financial Health Report
                </h1>
                <p className="text-sm text-gray-600">Comprehensive analysis for {userData.name}</p>
              </div>
            </div>
            <div className="flex items-center space-x-2">
              <Badge className="bg-gradient-to-r from-emerald-600 to-teal-600 text-white">
                AI Powered
              </Badge>
            </div>
          </div>
        </div>
      </header>

      <div className="container mx-auto px-4 py-8">
        {!reportGenerated ? (
          /* Report Generation Section */
          <div className="max-w-4xl mx-auto space-y-8">
            {/* Overview Card */}
            <Card className="overflow-hidden bg-gradient-to-br from-emerald-50/80 to-teal-50/80 border-2 border-emerald-200/50 shadow-xl">
              <CardHeader className="bg-gradient-to-r from-emerald-600 to-teal-600 text-white">
                <CardTitle className="flex items-center gap-3 text-2xl">
                  <div className="w-12 h-12 bg-white/20 rounded-full flex items-center justify-center">
                    <FileText className="h-6 w-6" />
                  </div>
                  <div>
                    <span>Generate Your Financial Health Report</span>
                    <div className="text-emerald-100 text-sm font-normal mt-1">
                      AI-powered analysis of your complete financial situation
                    </div>
                  </div>
                </CardTitle>
              </CardHeader>
              <CardContent className="p-8">
                <div className="grid md:grid-cols-2 gap-8">
                  <div className="space-y-6">
                    <div className="space-y-4">
                      <h3 className="text-xl font-semibold text-gray-900">What's Included:</h3>
                      
                      <div className="space-y-3">
                        <div className="flex items-start space-x-3">
                          <div className="w-8 h-8 bg-emerald-100 rounded-full flex items-center justify-center flex-shrink-0 mt-1">
                            <BarChart3 className="h-4 w-4 text-emerald-600" />
                          </div>
                          <div>
                            <h4 className="font-semibold text-gray-900">Complete Financial Analysis</h4>
                            <p className="text-gray-600 text-sm">Detailed review of savings, investments, debt, and spending patterns</p>
                          </div>
                        </div>
                        
                        <div className="flex items-start space-x-3">
                          <div className="w-8 h-8 bg-teal-100 rounded-full flex items-center justify-center flex-shrink-0 mt-1">
                            <Target className="h-4 w-4 text-teal-600" />
                          </div>
                          <div>
                            <h4 className="font-semibold text-gray-900">Goal Progress Assessment</h4>
                            <p className="text-gray-600 text-sm">Track your progress towards financial objectives and milestones</p>
                          </div>
                        </div>

                        <div className="flex items-start space-x-3">
                          <div className="w-8 h-8 bg-green-100 rounded-full flex items-center justify-center flex-shrink-0 mt-1">
                            <Zap className="h-4 w-4 text-green-600" />
                          </div>
                          <div>
                            <h4 className="font-semibold text-gray-900">Personalized Recommendations</h4>
                            <p className="text-gray-600 text-sm">AI-generated advice tailored to your specific situation</p>
                          </div>
                        </div>

                        <div className="flex items-start space-x-3">
                          <div className="w-8 h-8 bg-blue-100 rounded-full flex items-center justify-center flex-shrink-0 mt-1">
                            <Download className="h-4 w-4 text-blue-600" />
                          </div>
                          <div>
                            <h4 className="font-semibold text-gray-900">Downloadable PDF Report</h4>
                            <p className="text-gray-600 text-sm">Professional report you can save and share with advisors</p>
                          </div>
                        </div>
                      </div>
                    </div>

                    <Button 
                      size="lg" 
                      className="w-full bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-700 hover:to-teal-700 text-white shadow-lg hover:shadow-xl transition-all duration-300"
                      onClick={generateReport}
                      disabled={isGenerating}
                    >
                      {isGenerating ? (
                        <>
                          <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white mr-2"></div>
                          Generating Report...
                        </>
                      ) : (
                        <>
                          <FileText className="h-5 w-5 mr-2" />
                          Generate My Financial Report
                        </>
                      )}
                    </Button>
                  </div>

                  <div className="relative">
                    <div className="bg-white/60 backdrop-blur-sm rounded-2xl p-6 border border-white/40 shadow-lg">
                      <div className="space-y-4">
                        <div className="text-center">
                          <div className="w-16 h-16 bg-gradient-to-r from-emerald-600 to-teal-600 rounded-full flex items-center justify-center mx-auto mb-4">
                            <FileText className="h-8 w-8 text-white" />
                          </div>
                          <h3 className="text-lg font-semibold text-gray-900 mb-2">Your Profile Summary</h3>
                        </div>
                        
                        <div className="space-y-3 text-sm">
                          <div className="flex justify-between">
                            <span className="text-gray-600">Name:</span>
                            <span className="font-semibold">{userData.name}</span>
                          </div>
                          <div className="flex justify-between">
                            <span className="text-gray-600">Age:</span>
                            <span className="font-semibold">{userData.age}</span>
                          </div>
                          <div className="flex justify-between">
                            <span className="text-gray-600">Monthly Income:</span>
                            <span className="font-semibold"><CurrencyDisplay amount={userData.income} /></span>
                          </div>
                          <div className="flex justify-between">
                            <span className="text-gray-600">Monthly Savings:</span>
                            <span className="font-semibold"><CurrencyDisplay amount={userData.monthlySavings} /></span>
                          </div>
                          <div className="flex justify-between">
                            <span className="text-gray-600">Goal:</span>
                            <span className="font-semibold"><CurrencyDisplay amount={userData.goalAmount} /></span>
                          </div>
                          <div className="flex justify-between">
                            <span className="text-gray-600">Risk Tolerance:</span>
                            <span className="font-semibold capitalize">{userData.riskTolerance}</span>
                          </div>
                        </div>

                        <div className="pt-4 border-t border-gray-200">
                          <div className="flex items-center justify-center space-x-2 text-sm text-gray-600">
                            <CheckCircle className="h-4 w-4 text-green-500" />
                            <span>Profile Complete</span>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        ) : (
          /* Generated Report Section */
          <div className="max-w-6xl mx-auto space-y-8">
            {/* Report Header */}
            <div className="text-center space-y-4">
              <div className="inline-flex items-center space-x-2 bg-gradient-to-r from-emerald-600 to-teal-600 text-white px-6 py-3 rounded-full shadow-lg">
                <CheckCircle className="h-5 w-5" />
                <span className="font-semibold">Report Generated Successfully!</span>
              </div>
              <h2 className="text-3xl font-bold text-gray-900">Your Financial Health Report</h2>
              <p className="text-gray-600">Generated on {new Date().toLocaleDateString()}</p>
            </div>

            {/* Financial Health Score */}
            <Card className="overflow-hidden">
              <CardHeader className="bg-gradient-to-r from-emerald-600 to-teal-600 text-white">
                <CardTitle className="text-center text-2xl">Overall Financial Health Score</CardTitle>
              </CardHeader>
              <CardContent className="p-8">
                <div className="text-center space-y-4">
                  <div className="text-6xl font-bold bg-gradient-to-r from-emerald-600 to-teal-600 bg-clip-text text-transparent">
                    85/100
                  </div>
                  <div className="text-xl text-gray-600">Excellent Financial Health</div>
                  <Progress value={85} className="w-full max-w-md mx-auto h-4" />
                </div>
              </CardContent>
            </Card>

            {/* Key Metrics Grid */}
            <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
              <Card>
                <CardContent className="p-6 text-center">
                  <div className="w-12 h-12 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-4">
                    <PiggyBank className="h-6 w-6 text-green-600" />
                  </div>
                  <div className="text-2xl font-bold text-green-600">92%</div>
                  <div className="text-sm text-gray-600">Savings Rate</div>
                </CardContent>
              </Card>

              <Card>
                <CardContent className="p-6 text-center">
                  <div className="w-12 h-12 bg-blue-100 rounded-full flex items-center justify-center mx-auto mb-4">
                    <Target className="h-6 w-6 text-blue-600" />
                  </div>
                  <div className="text-2xl font-bold text-blue-600">78%</div>
                  <div className="text-sm text-gray-600">Goal Progress</div>
                </CardContent>
              </Card>

              <Card>
                <CardContent className="p-6 text-center">
                  <div className="w-12 h-12 bg-purple-100 rounded-full flex items-center justify-center mx-auto mb-4">
                    <TrendingUp className="h-6 w-6 text-purple-600" />
                  </div>
                  <div className="text-2xl font-bold text-purple-600">A+</div>
                  <div className="text-sm text-gray-600">Investment Strategy</div>
                </CardContent>
              </Card>

              <Card>
                <CardContent className="p-6 text-center">
                  <div className="w-12 h-12 bg-orange-100 rounded-full flex items-center justify-center mx-auto mb-4">
                    <AlertTriangle className="h-6 w-6 text-orange-600" />
                  </div>
                  <div className="text-2xl font-bold text-orange-600">B</div>
                  <div className="text-sm text-gray-600">Emergency Fund</div>
                </CardContent>
              </Card>
            </div>

            {/* Recommendations */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center space-x-2">
                  <Zap className="h-5 w-5 text-yellow-500" />
                  <span>AI Recommendations</span>
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="grid md:grid-cols-2 gap-6">
                  <div className="space-y-4">
                    <h3 className="font-semibold text-green-600 flex items-center">
                      <CheckCircle className="h-4 w-4 mr-2" />
                      Strengths
                    </h3>
                    <ul className="space-y-2 text-sm">
                      <li className="flex items-start space-x-2">
                        <Star className="h-4 w-4 text-yellow-500 mt-0.5 flex-shrink-0" />
                        <span>Excellent monthly savings rate of <CurrencyDisplay amount={userData.monthlySavings} /></span>
                      </li>
                      <li className="flex items-start space-x-2">
                        <Star className="h-4 w-4 text-yellow-500 mt-0.5 flex-shrink-0" />
                        <span>Well-defined financial goal of <CurrencyDisplay amount={userData.goalAmount} /></span>
                      </li>
                      <li className="flex items-start space-x-2">
                        <Star className="h-4 w-4 text-yellow-500 mt-0.5 flex-shrink-0" />
                        <span>Consistent tracking of expenses and income</span>
                      </li>
                    </ul>
                  </div>

                  <div className="space-y-4">
                    <h3 className="font-semibold text-orange-600 flex items-center">
                      <AlertTriangle className="h-4 w-4 mr-2" />
                      Improvement Areas
                    </h3>
                    <ul className="space-y-2 text-sm">
                      <li className="flex items-start space-x-2">
                        <div className="w-2 h-2 bg-orange-500 rounded-full mt-2 flex-shrink-0"></div>
                        <span>Build emergency fund to 6 months of expenses</span>
                      </li>
                      <li className="flex items-start space-x-2">
                        <div className="w-2 h-2 bg-orange-500 rounded-full mt-2 flex-shrink-0"></div>
                        <span>Diversify investments across different asset classes</span>
                      </li>
                      <li className="flex items-start space-x-2">
                        <div className="w-2 h-2 bg-orange-500 rounded-full mt-2 flex-shrink-0"></div>
                        <span>Consider tax-advantaged retirement accounts</span>
                      </li>
                    </ul>
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* Action Buttons */}
            <div className="flex justify-center space-x-4">
              <Button 
                onClick={downloadReport}
                className="bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-700 hover:to-teal-700 text-white"
              >
                <Download className="h-4 w-4 mr-2" />
                Download Report
              </Button>
              <Link href="/dashboard">
                <Button variant="outline">
                  Back to Dashboard
                </Button>
              </Link>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
